SELECT ESBJ.STD_IDX, M1.COURSE_IDX, M1.ENROLL_SEQ
		, COUNT(ESBJ.SBJ_ENROLL_IDX) AS CNT_FAIL_SBJ
		, GROUP_CONCAT(SBJ.SBJ_ID ORDER BY SBJ.SBJ_ID SEPARATOR ', ')  AS SBJ_IDS
FROM HS_TB_ENROLL_SUBJECT ESBJ
LEFT OUTER JOIN HS_TB_SBJ_COURSE_MAP M1
		ON M1.SBJ_COURSE_IDX = ESBJ.SBJ_COURSE_IDX
		AND M1.DEL_FLAG = 'N'
LEFT OUTER JOIN HS_TB_SUBJECT_INFO SBJ
		ON SBJ.SBJ_IDX = M1.SBJ_IDX
		AND SBJ.DEL_FLAG = 'N'
WHERE 1=1
AND ESBJ.TRIMESTER = '0119'
AND ESBJ.DEL_FLAG = 'N'
AND ESBJ.CANCEL_FLAG = 'N'
AND ESBJ.FINAL_GRADE = 'F'
GROUP BY ESBJ.STD_IDX, M1.COURSE_IDX, M1.ENROLL_SEQ
