version: "3"

services:

  heiis-backend:
    build: ./tomcat
    environment:
      - "TZ=Australia/Sydney"
    ports:
      - 38080:8080
    volumes:
      - "./tomcat/conf/server.xml:/opt/tomcat/conf/server.xml"
      - "./tomcat/conf/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml"
    # - "./tomcat/webapps/manager/META-INF/context.xml:/opt/tomcat/webapps/manager/META-INF/context.xml"
      - "../workspace-backend:/workspace/backend"
    command: "/opt/tomcat/bin/catalina.sh run"
  
  heiis-mysqldb:
    image: mysql/mysql-server:8.0
    environment:
      - "TZ=Australia/Sydney"
    ports:
      - "38306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=rootpass"
      - "MYSQL_USER=myuser"
      - "MYSQL_PASSWORD=mypass"
      - "MYSQL_DATABASE=sampledb"
    volumes:
      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    # - "../heiis-data/mysql:/var/lib/mysql"
