SELECT FEES.*
FROM HS_TB_OFFER_FEES FEES
WHERE FEES.OFFER_NO = '1'
ORDER BY
  CASE WHEN FEES.PAY_CD = 'PI000017' THEN 1
    WHEN FEES.PAY_CD = 'PI000011' THEN 2
    WHEN FEES.PAY_CD = 'PI000010' THEN 3
    ELSE 90 END
  , FEE_IDX
  