
/* show index */
SHOW INDEX FROM mytable FROM mydb;
SHOW INDEX FROM mydb.mytable;

/* add index */
ALTER TABLE HS_TB_CLS_ATTENDANCE ADD INDEX (CLS_IDX);
ALTER TABLE HS_TB_CLS_ATTENDANCE ADD INDEX (STD_IDX);
ALTER TABLE HS_TB_CLS_ATTEND_TIMES ADD INDEX (CLS_IDX);
