
-- select first idxs that have unique surnm

SELECT MIN(STD_IDX)
FROM HS_TB_STUDENT_INFO
WHERE 1=1
GROUP BY SURNM

-- delete the others

DELETE FROM HS_TB_STUDENT_INFO A
WHERE A.STD_IDX NOT IN (
	SELECT MIN(STD_IDX)
	FROM HS_TB_STUDENT_INFO
	WHERE 1=1
	GROUP BY SURNM
)