SELECT U1.IDX, U1.STD_IDX, U1.COURSE_IDX, U1.ENROLL_SEQ, U1.TRIMESTER
  , U1.UO_TYPE, U1.FORM_STATUS, U1.SBJ_CNT
FROM (
  SELECT U.IDX, U.STD_IDX, U.COURSE_IDX, U.ENROLL_SEQ, U.TRIMESTER
    , U.UO_TYPE, U.FORM_STATUS, U.SBJ_CNT
    , ROW_NUMBER() OVER (PARTITION BY U.STD_IDX, U.COURSE_IDX, U.ENROLL_SEQ, U.TRIMESTER ORDER BY U.APR_DATE DESC) AS EACH_ROW_NO
  FROM HS_TB_ENROLL_UNDER_OVER U	
  WHERE U.TRIMESTER = '0220'
  AND U.FORM_STATUS = 'UO_STAT_03'
) U1
WHERE U1.EACH_ROW_NO = 1