UPDATE HS_TB_APPLICATION_INFO A
LEFT OUTER JOIN HS_TB_COUNTRY_CODE N
		ON (N.NATIONALITY LIKE A.BORN_NATION_CD)
		AND N.DEL_FLAG = 'N'
SET A.BORN_NATION_CD = N.CODE
WHERE A.BORN_NATION_CD NOT REGEXP '^[0-9]{4}$'
AND IFNULL(A.BORN_NATION_CD,'') != ''
AND N.CODE IS NOT NULL