SELECT
		A.DAY_1,
		A.DAY_BEFORE,
		A.TODAY,
		A.DAY_1 BETWEEN A.DAY_BEFORE AND A.TODAY AS IS_BETEEN
FROM (
		SELECT 
				STR_TO_DATE( '27/08/2017', '%d/%m/%Y') AS DAY_1,
				STR_TO_DATE( '26/08/2017', '%d/%m/%Y') AS DAY_BEFORE,
				NOW(3) AS TODAY
) A