version: "3"

services:
  mysqlserver:
    container_name: myproject_mysql
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: "docker"
      MYSQL_USER: "local"
      MYSQL_PASSWORD: "local"

    volumes:
      # ---- Format: ----
      # HOST-DIRECTORY : DOCKER-DIRECTORY
      - ${MYSQL_BACKUP_FOLDER}:/backup/

    networks:
      app_net:
        ipv4_address: ${IP_MYSQL_SERVER}

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IP_SUBNET}
