SELECT DATE_FORMAT(NOW(), '%Y') AS Y1 FROM DUAL;

SELECT YEAR(NOW()) AS Y2 FROM DUAL;

SELECT LPAD(REPLACE(FORMAT(YEAR(NOW()), 0), ',', ''), 4, '0') AS STR_Y3 FROM DUAL;

SELECT CONCAT(LPAD(REPLACE(FORMAT(YEAR(NOW()), 0), ',', ''), 4, '0'), '1') AS STR_Y4 FROM DUAL;
