CREATE TABLE `test1` (
	`numb` INT(10) UNSIGNED NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

insert into test1 values (1);
insert into test1 values (2);
insert into test1 values (3);
insert into test1 values (999);
insert into test1 values (998);
insert into test1 values (997);


SELECT A.numb + 1 AS numb
FROM test1 AS A
WHERE A.numb + 1 NOT IN (
	SELECT numb
	FROM test1
)
AND A.numb <= 999
ORDER BY A.numb ASC
-- LIMIT 1
-- first item




SELECT A.SEQ + 1 AS NEXT_SEQ
FROM (
	SELECT CAST(IFNULL(SUBSTRING(A.APPLICANT_ID,CHAR_LENGTH(RTRIM(A.APPLICANT_ID))-2,3),'0') AS DECIMAL) AS SEQ
	FROM HS_TB_APPLICATION_INFO AS A
	WHERE IFNULL(A.MIG_TYPE,'N') != 'Y'
	AND A.STD_IDX = 14188
) AS A
WHERE A.SEQ + 1 NOT IN (
	SELECT CAST(IFNULL(SUBSTRING(B.APPLICANT_ID,CHAR_LENGTH(RTRIM(B.APPLICANT_ID))-2,3),'0') AS DECIMAL) AS SEQ
	FROM HS_TB_APPLICATION_INFO AS B
	WHERE IFNULL(B.MIG_TYPE,'N') != 'Y'
	AND B.STD_IDX = 14188
)
AND A.SEQ + 1 <= 999
ORDER BY NEXT_SEQ ASC LIMIT 1
